### ISSUE TITLE
Add Donate button

### ISSUE THREAD

**Issue by FireDeveloper** [ludwig-f/node-zpl#7]
Hello 😄
I am so excited that I found this library! I am building my first web app and its purpose is to automate manufacturing processes.
I believe that it can grow to a widely used library for Zebra printers and I would like to buy you a coffee if that's possible.

Ps. I have a ZD230, if you want to test something on that model you can reach me out.

**Comment by ludwig-f** [comment]
Thanks for the nice words, and the generous offer!

For now I think the library is in too early of a stage for me to feel comfortable taking donations, though 😅

It's really useful that you have access to a printer though - I'll ping you in this issue if the need occurs. Or I could drop you can email, if that works better for you?
